import type { Metadata } from "next";
import "../../app/globals.css";
import { ThemeProvider } from "next-themes";
import { routing, validateLocale } from '@/lib/i18n/routing';
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
// import { getServerSession } from "next-auth";
// import { authOptions } from "@/api/auth/[...nextauth]/route"; // Adjust path as needed
// import { AuthProvider } from "@/features/authentication/components/auth-provider";

export const metadata: Metadata = {
  title: "HPC Portal",
  description: "Generated by EPCD",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function BaseLocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  // const session = await getServerSession(authOptions);

  validateLocale(locale);
  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="bg-background text-foreground antialiased selection:bg-primary/10">
        <NextIntlClientProvider messages={messages} locale={locale}>
          {/* <AuthProvider session={session}> */}
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {/* This renders either the Login page or the Dashboard Layout */}
              {children}
            </ThemeProvider>
          {/* </AuthProvider> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}